[AIOE-628] update all codelabs to work with extension registry
AdobeDocs/project-firefly pull request #129
Opened 2021-09-09 06:18 UTC by Yu1986

## Description

Update all the codelabs in https://www.adobe.io/project-firefly/docs/resources/ to follow the extension registry
https://www.adobe.io/project-firefly/docs/guides/extensions/extension_migration_guide/

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-09 06:19 UTC, Yu1986 commented
@duynguyen  @icaraps  please take a look at the PR for https://jira.corp.adobe.com/browse/AIOE-628

2021-09-09 15:01 UTC, icaraps approved these changes
LGTM, just a few minor change requests 👍

2021-09-09 15:01 UTC, icaraps commented on src/pages/resources/cron-jobs/lesson2.md
> +pplication:
typo

2021-09-09 15:01 UTC, icaraps commented on src/pages/resources/cron-jobs/lesson1.md
> +Follow this [Creating your First Project Firefly Application](https://www.adobe.io/project-firefly/docs/getting_started/first_app/)
Please link to the internal markdown file for faster navigation links eg

`../../getting_started/first_app.md`

2021-09-10 04:24 UTC, Yu1986 commented
fix the typo and merge

2021-09-15 15:05 UTC, duynguyen requested changes
Thanks @Yu1986 .
For the "no extension" codelabs, that's all good.
For the extension ones, the manifest goes to ext.config..yaml, inside the extension folder. The app.config.yaml only contains reference of the ext.

2021-09-15 15:05 UTC, duynguyen commented on src/pages/resources/asset-compute-worker-ps-api/lesson1.md
> +After logging in, follow the prompts in the CLI and select the Organization, Project, and Workspace to use for the application. Choose the project and workspace you created when you set up your envir
typo `v1y`

2021-09-15 15:05 UTC, duynguyen commented on src/pages/resources/asset-compute-worker-ps-api/lesson1.md
> + ◯ DX Asset Compute Worker v1y
typo v1y

2021-09-15 15:05 UTC, duynguyen commented on src/pages/resources/asset-compute-worker-ps-api/lesson3.md
> +Because the SDK requires `apiKey` to be passed in the input params, update your `app.config.yaml` to include it.
For asset compute, the manifest info now moves to ext.config.yaml inside the extension folder, not app.

2021-09-15 15:05 UTC, duynguyen commented on src/pages/resources/custom-asset-compute-worker/lesson3.md
> +Edit `app.config.yaml` file and add `inputs` object, as shown below. This file describes IO Runtime action to be deployed.
For asset compute, the manifest info now moves to ext.config.yaml inside the extension folder, not app.

2021-09-15 15:05 UTC, duynguyen commented on src/pages/resources/customer-dashboard/lesson2.md
> +Then `app.config.yaml` is the cockpit of your Firefly app backend. It lists the declaration of serverless actions including name, source files, runtime kind, default params, annotations, and so on. Y
For ExC app, the manifest info now moves to ext.config.yaml inside the extension folder, not app.

2021-09-30 05:46 UTC, Yu1986 commented
@duynguyen fix all your input, please take a look again

2021-09-30 08:54 UTC, merged

2021-09-30 08:54 UTC, duynguyen commented
Thanks @Yu1986 . There're still some minor things to change but I've merged for now and will update directly.