Rename Project Firefly to App Builder
AdobeDocs/project-firefly pull request #147
Opened 2021-11-22 13:20 UTC by icaraps

2021-11-22 15:24 UTC, shazron requested changes

2021-11-22 15:24 UTC, shazron commented on src/pages/getting_started/common_troubleshooting.md
> +When your action code doesn't work as expected, you may want to investigate into what exactly went wrong. App Builder provides the [Logging SDK](https://github.com/adobe/aio-lib-core-logging), please
missed one reference here

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/barcode-reader/test.md
> +A App Builder App created with `aio app init` has a [jest](https://jestjs.io/) test structure by default. We'll show how to take advantage of it.
An App Builder App

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/customer-dashboard/lesson5.md
>  Now that you have it set up in Firefly app, next step is to create a marketing workflow in Campaign Standard which takes care of receiving external signals from the app and sending promotion emails.
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/debugging/lesson3.md
>  In our sample app, `logger` is used throughout the `hello` action. It is provided by the [Firefly's core Logging library](https://github.com/adobe/aio-lib-core-logging).
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/event-driven/lesson1.md
>  ## Initialize a Firefly app using CLI template
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/event-driven/lesson1.md
>  * [Creating your First Firefly App](../../getting_started/first_app.md)
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/event-driven/welldone.md
>  * Testing the flow by emitting event from firefly app
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/journaling-events/lesson1.md
>  # Lesson 1: Create an Event Provider using Firefly
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/journaling-events/lesson1.md
>  In this codelab, to provide an end to end solution, we need to have an event provider generating tons of events sending to journaling API, and the events provider need to be configurable to send x ev
missed this reference "use OpenWhisk Alarms Package in Firefly application"

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/spectrum-intro/lesson4.md
>  To initialize a Firefly app, let’s use the init command from the [CLI](https://github.com/adobe/aio-cli).
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/transclusions/_requirements.md
>  * [Creating your First Firefly App](../../getting_started/first_app.md)
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/videos/developers-live/deep-dive.md
>  description: Join us and see Firefly in action - code, security, headfull and headless apps, CI/CD and more.
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/videos/developers-live/deep-dive.md
>  Join us and see Firefly in action: code, security, headfull and headless apps, CI/CD and more.
missed this reference

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/videos/exploring/projects-and-workspaces.md
> +description: The App Builder team shared a short presentation about projects and workspaces and how to use customizations to help your team collaborate on building Firefly Applications.
missed this reference "to help your team collaborate on building Firefly Applications."

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/videos/exploring/projects-and-workspaces.md
> +The App Builder team shared a short presentation about projects and workspaces and how to use customizations to help your team collaborate on building Firefly Applications.
missed this reference "to help your team collaborate on building Firefly Applications."

2021-11-22 15:24 UTC, shazron commented on src/pages/resources/videos/overview/architecture.md
> +title: App Builder - A Breakdown of Firefly's Architecture
missed this reference "Firefly's Architecture"

2021-11-22 15:36 UTC, icaraps commented
Ping @sarahxxu

2021-11-22 16:08 UTC, icaraps commented
Thx @shazron for the review ! I just committed another batch of renames

2021-11-23 10:43 UTC, shazron approved these changes

2021-11-23 10:45 UTC, shazron commented on src/pages/resources/barcode-reader/test.md
> +A App Builder App created with `aio app init` has a [jest](https://jestjs.io/) test structure by default. We'll show how to take advantage of it.
@icaraps I think you missed this one

2021-11-23 17:16 UTC, icaraps commented
@sarahxxu good to merge ?

2021-11-24 03:10 UTC, shazron approved these changes

2022-01-11 06:03 UTC, merged