fix deployment links
AdobeDocs/project-firefly pull request #201
Opened 2022-06-21 15:55 UTC by MichaelGoberling

Closes https://github.com/AdobeDocs/project-firefly/issues/187

## Description

## Related Issue

https://github.com/AdobeDocs/project-firefly/issues/187

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-28 14:54 UTC, shazron requested changes

2022-06-28 14:54 UTC, shazron commented on src/pages/guides/deployment/index.md
> +If you do not own a [Runtime](/runtime) namespace, please [request trial access](https://adobeio.typeform.com/to/obqgRm).
the new trial form url is https://developer.adobe.com/app-builder/trial/

2022-06-28 14:54 UTC, shazron commented on src/pages/guides/deployment/index.md
> +The tradeoff is that developers will not be able to run code that uses [Files](https://github.com/adobe/aio-lib-files) or [State](https://github.com/adobe/aio-lib-state) SDKs, [cron jobs scheduler wi
missing a leading slash? `/app-builder/docs/resources/cron-jobs/`

2022-06-28 16:40 UTC, MichaelGoberling commented on src/pages/guides/deployment/index.md
> +The tradeoff is that developers will not be able to run code that uses [Files](https://github.com/adobe/aio-lib-files) or [State](https://github.com/adobe/aio-lib-state) SDKs, [cron jobs scheduler wi
Good catch! 👍

2022-06-29 03:25 UTC, shazron approved these changes

2022-06-29 03:25 UTC, merged