add: UI Template choices
AdobeDocs/project-firefly pull request #61
Opened 2020-09-30 09:08 UTC by rajarju

2020-09-30 09:30 UTC, meryllblanchet requested changes
Thanks for the contribution @rajarju !
I added some comments to update the PR.

2020-09-30 09:30 UTC, meryllblanchet commented on getting_started/first_app.md
> +1. If you included `Web Assets` under Adobe I/O App features you will be given two choices. One to include React Spectrum based UI teamplate or a Vanilla HTML/JS one
teamplate -> template

Could we link `[React Spectrum](https://react-spectrum.adobe.com/)`?

Could we mention that the Vanilla HTML/JS template is also based on `[Spectrum CSS](https://opensource.adobe.com/spectrum-css/)`?

Could we mention that both templates come with the boilerplate code needed to integrate the Project Firefly application within the `[Adobe Experience Cloud](https://github.com/AdobeDocs/project-firefly/blob/master/guides/exc_app/overview.md)`?

2020-10-21 21:44 UTC, sarahxxu commented
cc @rajarju do you want to update the pr?

2020-10-22 05:43 UTC, rajarju commented
@sarahxxu Thankd for the followup 
Updated the PR

2020-10-22 15:20 UTC, merged