feat: add new build and deploy hooks
AdobeDocs/project-firefly pull request #83
Opened 2020-12-07 02:21 UTC by shazron

WIP depends on a new aio-cli-plugin-app release.

2020-12-07 08:36 UTC, meryllblanchet approved these changes
LGTM, let's wait on the app plugin release to merge this one.

2020-12-07 10:03 UTC, shazron commented
@meryllblanchet updated with new workflow diagram(s) and text

2020-12-07 17:23 UTC, meryllblanchet reviewed
Thanks @shazron !

Before approving, what about the following changes?

- Add an additional diagram for the `aio app run` sequence and hooks
- Provide a simple use-case for each of the commands, showing why a developer would use the hooks.

Thinking loudly, something like:

- `aio app run` -> manage additional local development tooling that is not managed by the OOTB flow
- `aio app build` -> build action package or UI with additional steps, e.g. to support other frameworks or file types
- `aio app deploy` -> support additional deployment steps

WDYT? Would it be helpful for the developers when reading this doc?

2020-12-08 01:20 UTC, shazron commented
@meryllblanchet I'll add the other diagram. Good idea for the use cases! I'll add some

2020-12-08 06:50 UTC, shazron commented
@meryllblanchet done, ready for review

2020-12-08 06:56 UTC, shazron commented
@adobe/aio-cli-plugin-app@5.3.0 released

2020-12-08 09:07 UTC, meryllblanchet commented on guides/app-hooks.md
> +For example, pre and post hooks can be defined for the `run`, `build` and `deploy` command in the package.json file of your app. For the `build` and `deploy` commands, you can specify build and deplo
Typo: `commands in the package.json file` instead of `command in the package.json file`

2020-12-08 09:08 UTC, meryllblanchet commented on guides/app-hooks.md
> +## Use cases
What about renaming into `Typical use-cases for custom hooks`?

2020-12-08 09:10 UTC, meryllblanchet requested changes
Hi @shazron this looks great!

There are two minor changes. Meanwhile, I also thought that we could add a section called `Typical use-cases for scripts substitution` and document a few use-cases why a developer would substitute the build or deploy scripts.

WDYT?

2020-12-18 09:48 UTC, meryllblanchet approved these changes
LGTM

2020-12-18 09:48 UTC, merged